---
language: python
python:
  - 3.6

services: docker

addons:
  apt:
    update: true

install:
  - docker build -f docker/dockerfile -t pyslackers/sirbot-pyslackers:$TRAVIS_COMMIT -t pyslackers/sirbot-pyslackers:latest .

script:
  - docker run --entrypoint scripts/test.sh pyslackers/sirbot-pyslackers:$TRAVIS_COMMIT
