language: python

python:
- '3.6'
- 3.7-dev

matrix:
  allow_failures:
  - python: 3.7-dev

install:
  - pip install flake8

script:
  - flake8

deploy:
  provider: script
  script: bin/deploy.sh
  on:
    branch: master
    tags: false
    repo: pyslackers/sirbot-pyslackers
    python: '3.6'
