---
ansible_python_interpreter: /usr/bin/python3

email: contact@ovv.wtf
apt_upgrade: true
github_users:
  - ovv

provider: qemu
sirbot_host: sirbot.ovv.wtf

postgres_users:
  sirbot:
    password: snawad
    privileges:
      - {type: database, privileges: ['CREATE']}
postgres_listen_address: '172.17.0.1'

postgres_clients:
  - {db: sirbot, user: sirbot, address: 0.0.0.0/0}
  