---

- name: Configuration directory
  file:
    path: /etc/sirbot
    state: directory

- name: Environemnt
  template:
    src: etc/sirbot/env.j2
    dest: /etc/sirbot/.env
    owner: root
    group: root
    mode: 0600

- name: Docker configuration
  copy:
    src: ../../../../docker/docker-compose.prod.yml
    dest: /etc/sirbot/docker-compose.yml

- name: Traefik configuration
  template:
    src: ../../../../docker/traefik.toml.j2
    dest: /etc/sirbot/traefik.toml

- name: Acme configuration
  copy:
    content: ""
    dest: /etc/sirbot/acme.json
    force: no
    owner: root
    group: root
    mode: 0600

- name: Restart sirbot
  include_role: 
    name: pyslackers.docker
  vars:
    docker_services:
      sirbot:
        src: /etc/sirbot
        pull: True

- name: Successful deploy
  uri:
    url: "https://{{ sirbot_host }}/pyslackers/deploy"
    method: POST
    body:
      item: sirbot
      repo: https://github.com/pyslackers/sirbot-pyslackers
      token: "{{ sirbot_environment['deploy_token'] }}"
      version: "{{ sirbot_version }}"
    body_format: json
  when: notification
  delegate_to: localhost
