version: '3'

services:
  reverse-proxy:
    image: traefik:latest
    command: --api --docker
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443
      - 127.0.0.1:8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/sirbot/acme.json:/acme.json
      - /etc/sirbot/traefik.toml:/traefik.toml
    restart: always
   
  sirbot:
    image: pyslackers/sirbot-pyslackers:${SIRBOT_VERSION}
    env_file:
      - /etc/sirbot/.env
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.port=9000"
      - "traefik.frontend.rule=Host:${SIRBOT_HOST}"

volumes:
  db:
